import type { Initiative } from './types';

export const KRAKOW_CENTER = { latitude: 50.06747, longitude: 19.99169 };

export const initiatives: Initiative[] = [
  {
    id: 'garden',
    type: 'Misja',
    marker: 'M',
    color: '#2F6BFF',
    title: 'Ogród sąsiedzki w Parku Lotników',
    shortTitle: 'Ogród w Parku Lotników',
    distance: '250 m',
    address: 'Park Lotników Polskich',
    district: 'Czyżyny',
    latitude: 50.06655,
    longitude: 19.98855,
    date: 'Sobota, 11:00–14:00',
    people: 34,
    capacity: 50,
    points: 50,
    organizer: 'Ania i Sąsiedzi',
    description:
      'Zamieńmy pustą działkę w zielone miejsce spotkań. Posadzimy zioła i kwiaty oraz zbudujemy dwie ławki.',
    needs: ['8 osób', 'Narzędzia', 'Rośliny'],
    status: 'Otwarte dla wszystkich',
  },
  {
    id: 'cinema',
    type: 'Rajd',
    marker: 'R',
    color: '#7657FF',
    title: 'Kino plenerowe przy TAURON Arenie',
    shortTitle: 'Kino przy Arenie',
    distance: '100 m',
    address: 'ul. Stanisława Lema 7',
    district: 'Czyżyny',
    latitude: 50.06835,
    longitude: 19.99175,
    date: 'Piątek, 20:30',
    people: 18,
    capacity: 40,
    points: 80,
    organizer: 'Fundacja Dobry Kadr',
    description:
      'Sąsiedzki pokaz polskiego kina pod chmurką. Organizujemy ekran, leżaki i napisy dostępnościowe.',
    needs: ['Projektor', '6 osób', 'Leżaki'],
    status: 'Rajd społeczny',
  },
  {
    id: 'basket',
    type: 'Misja',
    marker: 'M',
    color: '#2F6BFF',
    title: 'Nocny basket przy Arenie',
    shortTitle: 'Basket przy Arenie',
    distance: '210 m',
    address: 'al. Pokoju · okolice Areny',
    district: 'Czyżyny',
    latitude: 50.06595,
    longitude: 19.99335,
    date: 'Czwartek, 19:00',
    people: 12,
    capacity: 20,
    points: 40,
    organizer: 'KS Wschód',
    description:
      'Otwarty trening i mini-turniej dla osób, które chcą poznać ekipę z dzielnicy.',
    needs: ['2 trenerów', 'Piłki', 'Woda'],
    status: 'Otwarte dla wszystkich',
  },
  {
    id: 'river',
    type: 'Zwiad',
    marker: 'Z',
    color: '#697586',
    title: 'Zwiad terenu wokół TAURON Areny',
    shortTitle: 'Zwiad wokół Areny',
    distance: '315 m',
    address: 'ul. Dąbska · okolice Areny',
    district: 'Czyżyny',
    latitude: 50.06755,
    longitude: 19.99610,
    date: 'Niedziela, 10:00–12:00',
    people: 21,
    capacity: 30,
    points: 60,
    organizer: 'Czysty Kraków',
    description:
      'Sprawdzimy teren wokół Areny i oznaczymy miejsca wymagające interwencji, poprawy dostępności lub uporządkowania.',
    needs: ['Rękawice', 'Worki', '9 osób'],
    status: 'Zwiad terenowy',
  },
];

export const categories = [
  ['Zieleń', 'leaf'],
  ['Kultura', 'color-palette'],
  ['Sport', 'basketball'],
  ['Integracja', 'people'],
  ['Wolontariat', 'heart'],
  ['Mobilność', 'bicycle'],
  ['Wydarzenia', 'calendar'],
  ['Turystyka', 'compass'],
  ['Edukacja', 'book'],
  ['Inne lokalne', 'grid'],
] as const;
