import type { Initiative } from './types';\n\nexport const KRAKOW_CENTER = { latitude: 50.0647, longitude: 19.945 };

export const initiatives: Initiative[] = [
  {
    id: 'garden',
    type: 'Misja',
    marker: 'M',
    color: '#2F6BFF',
    title: 'Ogród sąsiedzki na pustej działce',
    shortTitle: 'Ogród sąsiedzki',
    distance: '120 m',
    address: 'ul. Łąkowa 18',
    district: 'Grzegórzki',
    latitude: 50.0661,
    longitude: 19.9468,
    date: 'Sobota, 11:00–14:00',
    people: 34,
    capacity: 50,
    points: 50,
    organizer: 'Ania i Sąsiedzi',
    description:
      'Zamieńmy pustą działkę w zielone miejsce spotkań. Posadzimy zioła i kwiaty oraz zbudujemy dwie ławki.',
    needs: ['8 osób', 'Narzędzia', 'Rośliny'],
    status: 'Otwarte dla wszystkich',
  },
  {
    id: 'cinema',
    type: 'Rajd',
    marker: 'R',
    color: '#7657FF',
    title: 'Kino plenerowe nad Wisłą',
    shortTitle: 'Kino plenerowe',
    distance: '240 m',
    address: 'Bulwar Kurlandzki',
    district: 'Kazimierz',
    latitude: 50.0588,
    longitude: 19.9488,
    date: 'Piątek, 20:30',
    people: 18,
    capacity: 40,
    points: 80,
    organizer: 'Fundacja Dobry Kadr',
    description:
      'Sąsiedzki pokaz polskiego kina pod chmurką. Organizujemy ekran, leżaki i napisy dostępnościowe.',
    needs: ['Projektor', '6 osób', 'Leżaki'],
    status: 'Rajd społeczny',
  },
  {
    id: 'basket',
    type: 'Misja',
    marker: 'M',
    color: '#2F6BFF',
    title: 'Nocny basket dla młodzieży',
    shortTitle: 'Nocny basket',
    distance: '310 m',
    address: 'al. Pokoju 16',
    district: 'Grzegórzki',
    latitude: 50.0631,
    longitude: 19.9547,
    date: 'Czwartek, 19:00',
    people: 12,
    capacity: 20,
    points: 40,
    organizer: 'KS Wschód',
    description:
      'Otwarty trening i mini-turniej dla osób, które chcą poznać ekipę z dzielnicy.',
    needs: ['2 trenerów', 'Piłki', 'Woda'],
    status: 'Otwarte dla wszystkich',
  },
  {
    id: 'river',
    type: 'Szare miejsce',
    marker: '!',
    color: '#697586',
    title: 'Sprzątanie brzegu Wisły',
    shortTitle: 'Brzeg Wisły',
    distance: '420 m',
    address: 'Bulwar Inflancki',
    district: 'Dębniki',
    latitude: 50.0526,
    longitude: 19.9377,
    date: 'Niedziela, 10:00–12:00',
    people: 21,
    capacity: 30,
    points: 60,
    organizer: 'Czysty Kraków',
    description:
      'Wspólnie usuniemy odpady z brzegu i oznaczymy miejsca wymagające interwencji miasta.',
    needs: ['Rękawice', 'Worki', '9 osób'],
    status: 'Nierozwiązane miejsce',
  },
];

export const categories = [
  ['Zieleń', 'leaf'],
  ['Kultura', 'color-palette'],
  ['Sport', 'basketball'],
  ['Integracja', 'people'],
  ['Wolontariat', 'heart'],
  ['Mobilność', 'bicycle'],
  ['Wydarzenia', 'calendar'],
  ['Turystyka', 'compass'],
  ['Edukacja', 'book'],
  ['Inne lokalne', 'grid'],
] as const;\n